const actionTypes = {
  GET_HOME: "GET_HOME",
  SET_CUR_SONG_ID: "SET_CUR_SONG_ID",
  LOADING: "LOADING",
  PLAY: "PLAY",
  PLAYLIST: 'PLAYLIST',
  SET_CUR_SONG_DATA: "SET_CUR_SONG_DATA",
  SET_CUR_ALBUM_ID: "SET_CUR_ALBUM_ID",
  SET_RECENT: 'SET_RECENT',
  SEARCH: 'SEARCH',
  SET_ARTIST: 'SET_ARTIST',
  SET_ALBUM: 'SET_ALBUM',
  
};

export default actionTypes;
